---
abstract: 'A List of Modules required to Author Moose'
author:
  - 'Chris Prather  C<< <chris@prather.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-SDK-Moose
no_index:
  directory:
    - inc
    - t
requires:
  File::Find::Rule: 0
  Module::Info: 0
  Module::Install: 0
  Module::Install::AuthorRequires: 0
  Module::Install::ExtraTests: 0
  Test::Inline: 0
  Test::NoTabs: 0
  Test::Output: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perigrin/Task-SDK-Moose.git
version: 0.01
